### ISSUE TITLE
Add rubocop checks in GitHub Actions

### ISSUE THREAD

**Issue by ShockwaveNN** [onlyoffice-testing-robot/convert_service_testing#77]
Something like [this](https://github.com/ONLYOFFICE/doc-builder-testing/blob/d3738a22f392395efb8bac79fd74a9b6363056e7/.github/workflows/check.yml#L23)

**Comment by askonev** [comment]
When to close this issue? After fixing all RoboCop conflicts?

**Comment by askonev** [comment]
Added rubocop checks

**Comment by askonev** [comment]
Implemented in #83
